// SPDX-License-Identifier: Apache-2.0

/**
 * The compiled contracts, copied into src/generated by `npm run
 * frontend:config`. Loaded lazily, so the Compact runtime's WASM stays out of
 * the first page load.
 */

import { pipe } from "effect";
import { CompiledContract } from "@midnight-ntwrk/compact-js";

export type ContractName = "zkperp" | "pusdc";

const LOADERS: Record<ContractName, () => Promise<any>> = {
  // @ts-ignore — generated JavaScript, present after npm run frontend:config
  zkperp: () => import("../generated/zkperp/index.js"),
  // @ts-ignore
  pusdc: () => import("../generated/pusdc/index.js"),
};

const modules = new Map<ContractName, Promise<any>>();

export function contractModule(name: ContractName): Promise<any> {
  if (!modules.has(name)) modules.set(name, LOADERS[name]());
  return modules.get(name)!;
}

/** Neither contract has witnesses: every private input is a circuit argument. */
export async function compiledContract(name: ContractName): Promise<any> {
  const module = await contractModule(name);
  return pipe(CompiledContract.make(name, module.Contract), CompiledContract.withVacantWitnesses);
}
